apiVersion: v1
kind: Pod
metadata:
  name: kaniko-builder
spec: 
  initContainers: 
    - name:  busybox-share-init 
      image:  busybox:musl 
      command: 
        - sh 
      args: 
        - -c 
        - "cp -a /bin/* /busybox" 
      volumeMounts: 
        - name: busybox 
          mountPath: /busybox 
  containers: 
    - name: kaniko 
      image: gcr.io/kaniko-project/executor:debug
      command: 
        - sleep 
      args: 
        - infinity 
      env: 
        - name: PATH 
          value: /usr/local/bin:/kaniko:/busybox 
      workingDir: /home/jenkins/agent 
      volumeMounts: 
        - name: busybox 
          mountPath: /busybox 
          readOnly: true 
  volumes: 
  - name: busybox 
    emptyDir: {}
